import "./globals.css";
import '../components/home/home.css';
import { DM_Sans, Sora, Syne } from "next/font/google";
import Navbar from "@/components/shared/Navbar";

export const sora = Sora({
  subsets: ['latin']
})

export const dm_sans = DM_Sans({
  subsets: ['latin']
});

export const syne = Syne({
  subsets: ['latin']
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className={`${sora.className} min-h-screen flex flex-col bg-[#0b0d14] text-[#e8eaf0]`}>
        <Navbar />

        {children}
      </body>
    </html>
  );
}
